### PR TITLE
renaming folders & typos

### PR DESCRIPTION
**Pull request by mstomar698**
for Issue #17 
- [x] renamed folders in given order
- [x] Checked for more visual typos

### CODE REVIEW

**Comment by mstomar698** [comment]
is this reviewed or not??

**Comment by Saksham-Chauhan** [comment]
Hi @mstomar698 

Your changes are not as requested.
Please see #17 
> folder name must be small letter and component name must start with Capital letter

The folder names should not be capitalized.
Your PR is requesting to commit in the main branch of koders/Portfolio, please change it to commit to the dev branch.

**Comment by mstomar698** [comment]
ok I apply given changes.

**Comment by 1stdevfriend** [comment]
Good work! Feel free to apply at info@koders.in if you're looking for a job as an SDE

**Pull request merged**
